// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icuwltmlubwgbwszantw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljdXdsdG1sdWJ3Z2J3c3phbnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyODU1MzMsImV4cCI6MjA1MDg2MTUzM30.puIN7zD04oVNdS87hadv3Lag_Vq0URdjjvntZIYV38I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);